#!/bin/sh

#set METARCITIES="kbos kmsp ymml cyul kdca"

python "${HOME}${METARDIR}"/metar/__init__.py fetch "${METARCITIES}" 1> "${HOME}${METARDIR}"/metar-`date +%Y%m%d-%H%M`.tsv

sort "${HOME}${METARDIR}"/metar/metar-*.tsv" | uniq > "${HOME}${METARDIR}"/metar/all.tsv
